### ISSUE TITLE
negative test filter requires at least one property (trait / category) to exist within the tested assembly

### ISSUE THREAD

**Issue by Faizan2304** [xunit/xunit#1314]
_From @dmccaffery on June 6, 2017_

## Description

When executing the vstest runner with a negative filter on an assembly that does not contain at least one property of the specified type, an exception occurs.

## Steps to reproduce

1. Create a new unit test project that does not define a category property or trait.
2. Execute vstest with a `TestCaseFilter` that has a negative check for the category property or trait.
3. Exception will occur indicating that no test contains the specified category property or trait.

Example:

```
dotnet test "<assembly>" --no-build --configuration "Debug" --filter "Category!=Platform-Not-MacOS"
```

(this will call vstest.console underneath with a --TestCaseFilter and --TestAdapterPath)

## Expected behavior

All tests that do not have a category property or trait should execute based on the following logic: Category!=SomeValue is true when Category is not defined

## Actual behavior

```
Exception filtering tests: No tests matched the filter because it contains one or more properties that are not valid (Category). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again.
```

## Environment

```
~ dotnet --info
.NET Command Line Tools (1.0.4)

Product Information:
 Version:            1.0.4
 Commit SHA-1 hash:  af1e6684fd

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /Users/deavon/.dotnet/sdk/1.0.4
```

```
~ dotnet vstest
Microsoft (R) Test Execution Command Line Tool Version 15.0.0.0
Copyright (c) Microsoft Corporation.  All rights reserved.
```

_Copied from original issue: https://github.com/Microsoft/vstest/issues/841_

**Comment by Faizan2304** [comment]
I did some basic debugging and found that:

The exception is coming from this VSTest function https://github.com/Microsoft/vstest/blob/master/src/Microsoft.TestPlatform.CrossPlatEngine/Adapter/RunContext.cs#L69

xunit is sending only two properties (DisplayName, FullyQualifiedName) as supportedProperties when no test is having `Category` trait.
When any test is having  `Category` trait, xunit is sending three properties(Category, DisplayName, FullyQualifiedName) as supportedProperties.

**Comment by bradwilson** [comment]
That is the expected behavior. There is nothing special about using "Category" as a trait name.

**Comment by dmccaffery** [comment]
@bradwilson From xUnit’s perspective, this is absolutely true. From the VSTest perspective, at least with dotnet cli; filter expressions don’t allow for arbitrary trait key names... in piggybacking on Category to enable filtering of tests because I have no other recourse in an xplat world.

Since xunit supports all vstest properties by the nature of its completely free form TraitAttribute; the supportedProperties collection should include all of them regardless of whether or not they are defined. Either that, or vstest filter expression validation needs to allow for free form properties.

**Comment by dmccaffery** [comment]
https://github.com/automotiveMastermind/condo/commit/ae95308d8a3296d695d9e1fb3856f2c851e7550e

This is the commit where I changed from more meaningful trait names to category for everything. I may have misinterpreted the error I was getting at the time related to unsupported properties as being enforced by vstest rather than xunit since not all of these traits were defined at least once. Is there a way to supply xunit the supported property names explicitly instead of xunit building that list from introspection of usage? Not all test projects include all the traits and having to customize the filter expression per project based on which ones that particular project happens to be using at the time is very limiting from a build automation perspective.

These used to work with the xunit console runner, since it did not enforce trait filters to actually be in use within the project in order to evaluate them.

**Comment by dmccaffery** [comment]
https://github.com/xunit/xunit/blob/master/src/xunit.runner.visualstudio/Utility/TestCaseFilter.cs#L91

Answered my own question. Would it make sense to add a mechanism to supply some explicit values beyond display name, class name, and discovered traits for those of us who use well-known trait names across multiple projects? Perhaps as a property on custom trait attributes or discoverers?

**Comment by jamescrosswell** [comment]
@bradwilson this is definitely a problem - I'm just wondering whether it's a problem with xunit or with dotnet test. 

I've created [a very simple solution with two projects (slow and fast) demonstrating this issue](https://github.com/jamescrosswell/dotnet_test_filter). Using the same test runner with the same parameters, they behave totally differently. In one case, tests without a certain Trait are executed and in the other those tests are ignored. There's no sane world in which this is the "expected behavior"... 

![slow_filter](https://user-images.githubusercontent.com/728212/26868312-da4317e2-4b68-11e7-8b6a-5f5bd6cf2ef1.png)

**Comment by Faizan2304** [comment]
We have fixed this issue on vstest side: https://github.com/Microsoft/vstest/pull/845

**Comment by eakoning** [comment]
When running xUnit tests with Command Line task set to `dotnet test`, this problem still bothers me. Is there a way to fix that? I tried using the VSTest task, but it won't discover tests in **xUnit Test Project (.NET Core)** projects.

**Comment by dmccaffery** [comment]
@eakoning have you updated to Microsoft.NET.Test.Sdk >=15.5 in the csproj?

**Comment by eakoning** [comment]
@dmccaffery, I just did. This works like a charm! Thank you!

**Comment by jrr** [comment]
I still have this problem, with the following environment:

- VS2017
- SDK-style project targeting net462
- xunit 2.3.1
- Microsoft.NET.Test.Sdk 15.5

Both `dotnet test` (2.0.0) and `vstest.console.exe` (15.0.26929.2) produce this output:

```
[xUnit.net 00:00:01.3961216] Foo.Test: Exception filtering tests: No tests matched the filter because it contains one or more properties that are not valid (Bug). Specify filter expression containing valid properties (DisplayName, FullyQualifiedName) and try again.
```

What did I miss?

**Comment by bradwilson** [comment]
@jrr The issue is in VSTest, not xUnit.net. You should report it there.

**Comment by sphinxy** [comment]
>Both dotnet test (2.0.0) and vstest.console.exe (15.0.26929.2) produce this output
Have same wrong output on work project and normal output on experimental foobar project in another path, after running "dotnet vstest"
found that work project uses "Microsoft (R) Test Execution Command Line Tool Version 15.3.0-preview-20170628-02" and test project uses Microsoft (R) Test Execution Command Line Tool Version 15.7.0.
With "dotnet --info" found out why: 
work project has global.json that pointing to SDK 2.0.0
