### ISSUE TITLE
dotnet xunit not working on linux (while dotnet test does)

### ISSUE THREAD

**Issue by ThmX** [xunit/xunit#1365]
I'm developing on both osx and windows with .NET Core 2-Preview2, and would like to run my tests on a CI, in a docker container if possible. However, everything is working fine on OSX and Windows. But I'm unable to launch the test through `dotnet xunit` on Linux (docker and native).
While `dotnet test` would be good enough to dev, `dotnet xunit` gives the xml output which I need on the CI.

In summary, on linux `dotnet test` is working but `dotnet xunit` fails with the following message:
```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.5'.
```

Here's my `.csproj`:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="3.50.3" />
    <PackageReference Include="AutoFixture.Xunit2" Version="3.50.3" />
    <PackageReference Include="FluentAssertions" Version="4.19.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0-preview-20170517-02" />
    <PackageReference Include="xunit" Version="2.3.0-beta3-build3705" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta3-build3705" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta3-build3705" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\MyApp\MyApp.csproj" />
  </ItemGroup>
</Project>
```

Linux:
```bash
$ dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9

```

OSX:
```
$ dotnet --info
.NET Command Line Tools (2.0.0-preview2-006497)

Product Information:
 Version:            2.0.0-preview2-006497
 Commit SHA-1 hash:  06a2093335

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/share/dotnet/sdk/2.0.0-preview2-006497/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0-preview2-25407-01
  Build    : 40c565230930ead58a50719c0ec799df77bddee9
```

**Comment by felixhao28** [comment]
Same for me but I get ``Version for package `dotnet-xunit` could not be resolved.`` instead.

**Comment by brendandburns** [comment]
I'm running into this as well. anyone have ideas/workarounds?  It seems like `TargetFramework` is being ignored or somesuch...

**Comment by hannasm** [comment]
I am also facing this issue trying to run on dotnet core 2.0.0-preview3-006729

I noticed when i used xunit 2.3.0-beta2-build3683 instead of 2.3.0-beta3-build3705, it changed the error message to:

       > Alternatively, install the framework version '1.0.4'.

Digging into ~/.Nuget/packages/dotnet-xunit/2.3.0-beta3-build3705/ i ran 'find -iname *runtimeconfig*' which gives

          > ./tools/netcoreapp1.0/xunit.console.runtimeconfig.json
          > ./lib/netcoreapp1.0/dotnet-xunit.runtimeconfig.json

I changed the version in both files (not sure if both was really necesarry) from

          "version": "1.0.5"
to 
          "version": "2.0.0-preview3-006729"

and that got xunit running. 

I'm sure there's a better way to fix this instead of screwing around with files in the nuget package cache but it is _a solution_

**Comment by bradwilson** [comment]
Thanks, I'm trying to dragoon one of the .NET team into helping me figure out the best strategy to fix the issue. 😁

**Comment by natemcmaster** [comment]
Which versions of the .NET Core runtime do you have installed? 
```sh
# where is dotnet?
dotnet_home=$(dirname $(readlink -f $(which dotnet)))
ls $dotnet_home/shared/Microsoft.NETCore.App/
```
Chances are good this will be solved by doing as the error message suggests: install the right framework version. https://www.microsoft.com/net/download/core#/runtime

**Comment by ThmX** [comment]
@bradwilson thanks, appreciated

@natemcmaster 1) the runtime are there along the sdk for .net core 2 (as mentioned on my dotnet info trace), as I'm using the sdk installed inside the Microsoft dotnet docker container 2) why install the runtime for .net core 1 when targeting .net core 2, that would be architecturally incorrect and very confusing

**Comment by brendandburns** [comment]
@ThmX what is weird is that I have the framework version set to something else in my test directory. It seems that using xunit requires that I install a different framework version...

**Comment by natemcmaster** [comment]
Some clarification:

1. .NET Core does not auto roll-foward you to new major or minor versions by default. It will only rollfoward to patch updates.
2. Tools installed via DotNetCliToolReference operates independently of the `TargetFramework` property in that project.
3.  To mitigate (1), dotnet-xunit has chosen to use the "prefercliruntime" option which rolls forward to new minor versions, but not major versions.
4. dotnet-xunit is a .NET Core 1.0 app. The CLI is trying to run it as a 1.0 app but can't find a runtime that works.

Solutions:
- dotnet-xunit can update to target netcoreapp2.0. @bradwilson - you should be able to cross target dotnet-xunit.dll to netcoreapp1.0 too for backwards-compat.
- Install .NET Core 1.0.5

**Comment by natemcmaster** [comment]
FYI - under the hood, here is how dotnet picks a runtime for CLI verbs installed from a NuGet package: https://github.com/dotnet/cli/blob/release/2.0.0/src/Microsoft.DotNet.Cli.Utils/CommandResolution/PackagedCommandSpecFactoryWithCliRuntime.cs#L22-L54

**Comment by ThmX** [comment]
Oh great answer, thanks a lot, now I get the actual problem, I'll try it out with the .net core 1 runtime as a workaround waiting for the full fix. Thanks again!

But now I'm confused about something else, why is it working on Windows and OSX knowing I don't have .net core 1 installed on them?

**Comment by natemcmaster** [comment]
> why is it working on Windows and OSX knowing I don't have .net core 1 installed on them?

You probably do, and the issue repro-ed on Windows when I removed .NET core 1.x completely. You can find where .NET Core is coming from by doing this in powershell
```ps1
$env:COREHOST_TRACE=1
dotnet xunit --help 2>&1 | sls 'Chose FX Version'
```
Look for a line that looks like this:
```
Chose FX version [C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.5]
```

**Comment by bradwilson** [comment]
So it turns out there are two separate but related issues.

* The current compilation of `dotnet-xunit.dll` targets 1.0.5 because the CI machine has 1.0.5 installed. This needs to be changed to target 1.0.0 instead.
* The `prefercliruntime` file is ignored when the major versions don't match (i.e., when running .NET Core 2.x with a program compiled against 1.x), so we will also need to multi-target both 1.0 and 2.0 for `dotnet-xunit.dll`. This, too, will eventually need to be "stuck" to 2.0.0 once the RTM ships.

Thanks to @natemcmaster for once again being my "loading issues" life saver. 😉

**Comment by bradwilson** [comment]
FWIW, this is not a Linux issue. You probably just happened to have 1.0.5 installed on your Windows and OS X boxes, which allowed everything to run. And since `dotnet-xunit` only requires 1.x (and not 2.x), then it ran with 1.0.5, but your tests ran with 2.0.0-preview2 (the former uses `dotnet-xunit.runtimeconfig.json`; the latter uses the `.runtimeconfig.json` file from your unit tests, which will be pointing to 2.0).

**Comment by bradwilson** [comment]
And one last issue: if the unit test project doesn't have a `.runtimeconfig.json`, we should be using the one from `xunit.console.dll` so that it can pick up an appropriate minimum framework version. When I try to run 2.0 tests on my Windows machine right now, I see this:

```
 PS> dotnet xunit
Detecting target frameworks in 1.csproj...
Building for framework netcoreapp2.0...
  1 -> C:\Users\brad\Desktop\1\bin\Debug\netcoreapp2.0\1.dll
Running .NET Core tests for framework netcoreapp2.0...
xUnit.net Console Runner (64-bit .NET Core 4.0.0.0)
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
```

That `.NET Core 4.0.0.0` is telling me that we're using 1.0 to attempt to run 2.0 tests.

Lots of fun discoveries here. 😛

**Comment by brendandburns** [comment]
@natemcmaster if I want to have dotnet 2.0 installed (b/c that's the only one that works on Debian 9) how do I install the 1.0.5 framework?

Thanks!

**Comment by bradwilson** [comment]
I think you're just going to have to wait for us to fix the issue.

**Comment by bradwilson** [comment]
Fixed in 2.3 beta 4, shipping today.

**Comment by shawnmclean** [comment]
It seems 2.3.0-beta4-build3742 didn't fix this issue for me.

The container I'm trying to run test in is `microsoft/dotnet:2.0-sdk`.

`dotnet xunit` throws this error:

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.4' was not found.
  - Check application dependencies and target a framework version installed at:
      /
  - Alternatively, install the framework version '1.0.4'.
Exited with code 131
```

**Comment by wsun4ipipeline** [comment]
I got same problem even I update xunit/xunit.runner to 2.3.0.beta4-build3472.  I was running the app under Docker with FROM "microsoft/aspnetcore-build:2.0.0-jessie", and I still got failed.
my logs like below:
Step 9/11 : RUN dotnet xunit -xml /app/testOutput/LP2ApiTestResults.xml
 ---> Running in 4d406f83f329

[91mIt was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '1.0.5' was not found.
  - Check application dependencies and target a framework version installed at:
      /
[0m[91m  - Alternatively, install the framework version '1.0.5'.
[0mThe command '/bin/sh -c dotnet xunit -xml /app/testOutput/LP2ApiTestResults.xml' returned a non-zero code: 131

**Comment by wsun4ipipeline** [comment]
Looks the issue resolved after I   add   <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta4-build3742" />  with matching version number.

<ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.3.0" />
    <PackageReference Include="xunit" Version="2.3.0-beta4-build3742" />
    <PackageReference Include="xunit.runner.console" Version="2.3.0-beta4-build3742" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.0-beta4-build3742" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.0-beta4-build3742" />
  </ItemGroup>

**Comment by mleenhardt** [comment]
I'm still hitting this when running in a CentOS 7 container with .NET Core 2.0.0 and 2.0.4 installed.

csproj:
```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.TestHost" Version="2.0.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.5.0" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="xunit" Version="2.3.1" />
    <PackageReference Include="xunit.runner.console" Version="2.3.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.3.1" />
    <DotNetCliToolReference Include="dotnet-xunit" Version="2.3.1" />
  </ItemGroup>
</Project>
```

**Comment by bradwilson** [comment]
@mleenhardt Please open a new issue with a repro project.
