### ISSUE TITLE
Analyzer gives false positive for Zero and minus Zero InlineData

### ISSUE THREAD

**Issue by gpetrou** [xunit/xunit#1489]
Try adding the following test in Analyzers  InlineDataShouldBeUniqueWithinTheoryTests.ForDuplicatedInlineDataMethod.

     [Fact]
     public async void DoesNotFindWarning_ForZeroAndNegativeZeroInlineData()
     {
           var diagnostics = await CodeAnalyzerHelper.GetDiagnosticsAsync(analyzer,
                    "public class TestClass" +
                    "{" +
                    "   [Xunit.Theory]" +
                    "   [Xunit.InlineData(0.0)]" + Environment.NewLine +
                    "   [Xunit.InlineData(-0.0)]" + Environment.NewLine +
                    "   public void TestMethod(double x) { }" +
                    "}");

                Assert.Empty(diagnostics);
      }

Shouldn't this pass?

**Comment by bradwilson** [comment]
Integers don't treat positive and negative zero as distinct values; only floating point values do.

**Comment by gpetrou** [comment]
I updated the code.

**Comment by bradwilson** [comment]
I'm still not sure this is a failure.

From an equality standpoint, `0d` and `-0d` are equal values, even though they may be represented differently. How exactly do you intend to use this in a test where they turn out to be different?

**Comment by bradwilson** [comment]
As an example, look at the lengths people have to go to in order to even be able to tell the difference: https://stackoverflow.com/questions/4739795/how-can-i-test-for-negative-zero

**Comment by gpetrou** [comment]
Yes, I know :)
We actually have some methods to check for absolute/relative equality of floats/doubles that we use for Linear Algebra/Computational Geometry libraries.
Internally they use calls such as:
long doubleAsInt64Bits = *((long*)&value);
So, among other theories for testing them we check that comparing left/right values such as 0.0, 0.0 and 0.0, -0.0 will give the same result even though they are represented differently as longs.
I see you have some related tests in https://github.com/xunit/xunit/commit/eb78697a8d460f8bda4195e4d72386975665c0dd
Anyway, the analyzers shipped with xUnit are very useful (great work!), so if this is by design, perhaps there is a way to disable the analyzers rule only for these theories and not the entire assembly?

**Comment by gpetrou** [comment]
Seems like just using "#pragma warning disable xUnit1025" just for the InlineData does the trick.

**Comment by bradwilson** [comment]
I'm convinced. 😄

**Comment by marcind** [comment]
Since the analyzers have access to the code as written it should be fairly easy to detect `0.0` vs. `-0.0`

**Comment by wachulski** [comment]
Interesting, I'll take it.
