### ISSUE TITLE
xUnit1026 false positive: argument is warned as unused but it is an out parameter of mocked interface

### ISSUE THREAD

**Issue by lioobayoyo** [xunit/xunit#2139]
If a theory parameter is used as an `out` parameter in an expression tree, the analyzer doesn't recognize that and flag it as unused.

Repro code:
```
        interface ITest
        {
            bool TrySomething(out string someOutput);
        }

        [Theory]
        [InlineData("42")]
        public void TestWithFalsePositiveixUnit1026(string thisParameterIsUsed)
        {
            var mock = new Mock<ITest>();
            mock.Setup(x => x.TrySomething(out thisParameterIsUsed)).Returns(true);
        }
```

Gives warning:

```
Warning	xUnit1026	Theory method 'TestWithFalsePositiveixUnit1026' on test class 'MyTestClass' does not use parameter 'thisParameterIsUsed'
```

Nuget packages versions: 

xunit 2.4.1
xunit.analyzer 0.10.0
Moq 4.14.5

**Comment by bradwilson** [comment]
Would like to understand whether this bug is because of `out` or because of the expression tree on the Mock. A simpler repro would help us understand which problem (or maybe both) exists.

**Comment by lioobayoyo** [comment]
@bradwilson 

If I remove both `out` in the repro, I don't have any warning., that really looks like the out.

OK:
```
        interface ITest
        {
            bool TrySomething(string someOutput);
        }

        [Theory]
        [InlineData("42")]
        public void TestOk(string thisParameterIsUsed)
        {
            var mock = new Mock<ITest>();
            mock.Setup(x => x.TrySomething(thisParameterIsUsed)).Returns(true);
        }
```

PS: Also, I forgot to indicate the package versions I am using, I added them in the question.

**Comment by lioobayoyo** [comment]
I removed Moq from the repro from the equation here :

Fals positive warning:
```
        interface ITest
        {
            bool TrySomething(out string someOutput);
        }

        class SomeImplementation : ITest
        {
            public bool TrySomething(out string someOutput)
            {
                someOutput = "foo";
                return true;
            }
        }

        [Theory]
        [InlineData("42")]
        public void TestWithFalsePositiveixUnit1026(string thisParameterIsUsed)
        {
            var testImplementation = new SomeImplementation();
            var result = testImplementation.TrySomething(out thisParameterIsUsed);
        }
```

I note that Visual Studio colors `thisParameterIsUsed` like any unused variable, in dark grey.

![image](https://user-images.githubusercontent.com/1547293/91669045-1ad00300-eb12-11ea-8aa3-6e0f61834d94.png)

**Comment by randomnoise** [comment]
This issue is similar to #1802 and fixed in xunit/xunit.analyzers#137. I think it can be closed @bradwilson.

**Comment by bradwilson** [comment]
@randomnoise I can confirm that this issue is still there in `1.3.0-pre.12`.

And I believe what I wrote in #1969 probably applies here as well:

> We use Roslyn to do the analysis of what's used or not:
> 
> https://github.com/xunit/xunit.analyzers/blob/4c1c7e2fce2d65e473c8eef2ba83ec0b37d3c144/src/xunit.analyzers/X1000/TheoryMethodShouldUseAllParameters.cs#L54
> 
> It seems to me like this is might be a bug or missing feature on the Roslyn side.

**Comment by bradwilson** [comment]
Closing because it's a Roslyn issue.
