### ISSUE TITLE
CSC : warning AD0001: The analysis "Xunit.Analyzers.AssertEqualLiteralValueShouldBeFirst" has thrown an exception of type "System.NullReferenceException" with the message "Object reference not set to an instance of an object".

### ISSUE THREAD

**Issue by Kiwibomber** [xunit/xunit#2258]
I'm getting these exceptions thrown by the 0.10.0 analyzer on Microsoft Visual Studio Enterprise 2019 Version 16.8.5:

CSC : warning AD0001: The analysis "Xunit.Analyzers.AssertEqualLiteralValueShouldBeFirst" has thrown an exception of type "System.NullReferenceException" with the message "Object reference not set to an instance of an object".

**Comment by bradwilson** [comment]
Do you have an example project which repros the issue?

**Comment by Kiwibomber** [comment]
Yes, you can repeat the mistake yourself.
For this you just need to write an assert in the constructor. For example like this: 

`using Xunit;

namespace Testing
{
    public class UnitTest1
    {
        public UnitTest1()
        {
            Assert.Equal(new System.Collections.Generic.List<string>(10).Count, 10);
        }
    }
}
`

By the way: I had to search for several hours in our solution until I understood how this error occurs. 
I will now make sure that there is no assert in any constructor (but my colleagues always come up with strange ideas). 
But I think it would certainly make sense for the upcoming version, if it comes there not to a warning, but to a display in Visual Studio.

**Comment by nbalakin** [comment]
It seems to be already fixed in https://github.com/xunit/xunit.analyzers/commit/fa8ccb27c94d0cb8b919fb6852157230c63741d6.

**Comment by Kiwibomber** [comment]
I can still reproduce the error, this time with the following setup: 
- Microsoft Visual Studio Community 2019 Version 16.10.2.
- <TargetFramework>net48</TargetFramework>
- <PackageReference Include="xunit" Version="2.4.1" />

It seems that the error still exists.

**Comment by nbalakin** [comment]
The error still exists in the NuGet package because the package is published from a much older commit.
So the error should be gone as soon as the authors publish an updated package.

**Comment by vdanche** [comment]
Also repro VS 16.4.25/ 16.7.18 /16.11

**Comment by Kiwibomber** [comment]
Still open because no newer Version.
This item can close when we got a new version higher them 2.4.1.
