### ISSUE TITLE
Changes to TheoryData break tests with arrays of objects

### ISSUE THREAD

**Issue by MattVane** [xunit/xunit#3031]
After today's upgrade to xUnit 2.9.1 we've found an issue with tests that are parameterized by arrays of objects e.g.

  ```
  [Theory]
    [MemberData(nameof(ExampleParameters))]
    public void ExampleParameterizedTestMethod(string[] values)
    {
        Assert.All(values, s => Assert.True(s.Length < 10));
    }

    public static TheoryData<string[]> ExampleParameters =>
        new TheoryData<string[]>
        {
            { new string[] { "0", "2", "4" } },
            { new string[] { "0", "8", "6" } }
        };
```

This code consistently fails with _"Test method expected 1 parameter value but n parameter values were provided"_ as if it interpreting the array as a set of parameters instead of a single parameter. 

Release notes state _"any code that was previously depending on it returning IEnumerable<object[]> may need to be rewritten (i.e., casting the data to IEnumerable<object[]> explicitly before enumerating)."_ but I honestly don't see where I could be explicitly casting/specifying the types any more?

When T is a primitive (e.g. int) everything seems to work okay, but not so much with objects.

It doesn't seem to fail if we use _List<T>_ instead of _T[]_ so we have a workaround for now, but I thought you guys should be aware

**Comment by bradwilson** [comment]
Confirmed, it fails for `TheoryData<AnyType[]>` because of the covariance of `IEnumerable<object[]>` being type-compatible with `IEnumerable<AnyType[]>`. It doesn't affect `TheoryData<List<AnyType>>` because that's not covariant.

Fix available in v2 `2.9.2-pre.2` https://xunit.net/docs/using-ci-builds

I'll wait a couple days to see if any other hot issues come in before shipping this to NuGet as an RTM.

**Comment by afuersch** [comment]
I still experience this issue in v2.9.2 when using the `ClassData` attribute with a class derived from `TheoryData`. 
See the modified example with the exceptions next to the `Add` calls.
```csharp
    [Theory]
    [ClassData(typeof(ExampleParameters))]
    public void ExampleParameterizedTestMethod(string[] values)
    {
        Assert.All(values, s => Assert.True(s.Length < 10));
    }

    private sealed class ExampleParameters : TheoryData<string[]>
    {
        public ExampleParameters ()
        {
            Add(new string[] { "0" }); //System.ArgumentException: Object of type 'System.String' cannot be converted to type 'System.String[]'.
            Add(new string[] { "0", "2" }); //System.InvalidOperationException: The test method expected 1 parameter value, but 2 parameter values were provided.
            Add(new string[] { "0", "2", "4" }); //System.InvalidOperationException: The test method expected 1 parameter value, but 3 parameter values were provided.
        }
    }
```

**Comment by bradwilson** [comment]
Bad news: I can reproduce this.

Good news: I can't reproduce in v3, so the version of TheoryData in v3 works correctly. The 1.0 release of v3 is coming before year's end (I'm planning to release a final 0.6.0 pre-release shortly, then after a couple weeks of stability testing, release 1.0.)

I'll look to see whether I can solve this for v2 or not. The difference in design between TheoryData in v2 and v3 doesn't allow me to back-port the v3 code, so that's not an available solution.

**Comment by bradwilson** [comment]
@afuersch Your fix is available in `2.9.3-pre.5` https://xunit.net/docs/using-ci-builds

**Comment by bradwilson** [comment]
I have just shipped 2.9.3: https://xunit.net/releases/v2/2.9.3
