### ISSUE TITLE
xunit v3 2.0.0 - Rider - unable to run tests

### ISSUE THREAD

**Issue by MattParkerDev** [xunit/xunit#3196]
On the latest Rider version (2024.3.6), I'm unable to run tests using xunit v3 2.0.0.

![Image](https://github.com/user-attachments/assets/11d12fd2-7578-40ba-8bb0-37811725c45c)

If this is an issue with Rider, feel free to close this issue and I shall raise an issue on YouTrack :)

There is an existing/similar issue here, but it was fixed with the latest Rider release.
https://youtrack.jetbrains.com/issue/RSRP-499789
```
Test has not run

Last runner error: Method not found: 'System.Threading.Tasks.ValueTask Xunit.v3.InProcessFrontController.Find(Xunit.Sdk.IMessageSink, Xunit.Sdk.ITestFrameworkDiscoveryOptions, System.Func`2<Xunit.Sdk.ITestCase,Boolean>, System.Type[], System.Func`3<Xunit.Sdk.ITestCase,Boolean,System.Threading.Tasks.ValueTask`1<Boolean>>)'., reason: System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask Xunit.v3.InProcessFrontController.Find(Xunit.Sdk.IMessageSink, Xunit.Sdk.ITestFrameworkDiscoveryOptions, System.Func`2<Xunit.Sdk.ITestCase,Boolean>, System.Type[], System.Func`3<Xunit.Sdk.ITestCase,Boolean,System.Threading.Tasks.ValueTask`1<Boolean>>)'. at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.TestDiscoverer.Run(CancellationToken ct) at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine) at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.TestDiscoverer.Run(CancellationToken ct) at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.XUnitRunner.RunTestsAsync(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.XUnit3\XUnitRunner.cs:line 76

--- EXCEPTION #1/2 [RdFault]
Message = “
  Method not found: 'System.Threading.Tasks.ValueTask Xunit.v3.InProcessFrontController.Find(Xunit.Sdk.IMessageSink, Xunit.Sdk.ITestFrameworkDiscoveryOptions, System.Func`2<Xunit.Sdk.ITestCase,Boolean>, System.Type[], System.Func`3<Xunit.Sdk.ITestCase,Boolean,System.Threading.Tasks.ValueTask`1<Boolean>>)'., reason: System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask Xunit.v3.InProcessFrontController.Find(Xunit.Sdk.IMessageSink, Xunit.Sdk.ITestFrameworkDiscoveryOptions, System.Func`2<Xunit.Sdk.ITestCase,Boolean>, System.Type[], System.Func`3<Xunit.Sdk.ITestCase,Boolean,System.Threading.Tasks.ValueTask`1<Boolean>>)'.
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.TestDiscoverer.Run(CancellationToken ct)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.TestDiscoverer.Run(CancellationToken ct)
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.XUnitRunner.RunTestsAsync(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.XUnit3\XUnitRunner.cs:line 76
”
ReasonTypeFqn = System.MissingMethodException
ReasonText = “
  System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask Xunit.v3.InProcessFrontController.Find(Xunit.Sdk.IMessageSink, Xunit.Sdk.ITestFrameworkDiscoveryOptions, System.Func`2<Xunit.Sdk.ITestCase,Boolean>, System.Type[], System.Func`3<Xunit.Sdk.ITestCase,Boolean,System.Threading.Tasks.ValueTask`1<Boolean>>)'.
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.TestDiscoverer.Run(CancellationToken ct)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.TestDiscoverer.Run(CancellationToken ct)
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.XUnitRunner.RunTestsAsync(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.XUnit3\XUnitRunner.cs:line 76
”
ReasonMessage = “Method not found: 'System.Threading.Tasks.ValueTask Xunit.v3.InProcessFrontController.Find(Xunit.Sdk.IMessageSink, Xunit.Sdk.ITestFrameworkDiscoveryOptions, System.Func`2<Xunit.Sdk.ITestCase,Boolean>, System.Type[], System.Func`3<Xunit.Sdk.ITestCase,Boolean,System.Threading.Tasks.ValueTask`1<Boolean>>)'.”
StackTraceString = “
  at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.Activation.ServerMessageBroker.SendMessage(IMessage message) in SendMessage.il:line IL_0077 mvid FCFC
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<RunTests>b__8_1()
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.ThrowIf[TException](Task task, Task signallingTask, Func`1 exceptionFactory) in ThrowIf.il:line IL_0118 mvid FCFC
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.CancelIf(Task task, CancellationToken ct, TaskCreationOptions options) in CancelIf.il:line IL_0126 mvid FCFC
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.RunTests(CancellationToken cancelCt, CancellationToken abortCt) in RunTests.il:line IL_00AE mvid FCFC or RunTests.il:line IL_02D6 mvid FCFC
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerRunStrategy.Run(IUnitTestRun run) in Run.il:line IL_01C8 mvid FCFC
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.StartCore(CancellationToken onCancel, CancellationToken onAbort) in StartCore.il:line IL_01E7 mvid FCFC or StartCore.il:line IL_03B3 mvid FCFC
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.<>c.<StartCore>b__37_0(ExceptionDispatchInfo e) in UnitTestRun.il:line IL_0000 mvid FCFC
     at JetBrains.Util.Special.GeneralUtil.WithNotNull[T](T item, Action`1 F) in WithNotNull.il:line IL_0016 mvid 91BE
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.StartCore(CancellationToken onCancel, CancellationToken onAbort) in StartCore.il:line IL_01E7 mvid FCFC or StartCore.il:line IL_03B3 mvid FCFC
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.Start(CancellationToken onCancel, CancellationToken onAbort) in Start.il:line IL_0182 mvid FCFC
”
ExceptionPath = Root.InnerException
ClassName = JetBrains.Rd.Tasks.RdFault
HResult = COR_E_EXCEPTION=80131500
Source = System.Private.CoreLib
Data.ThreadLocalDebugInfo = “
  call `ServerSocket-<noname>.JetBrains.ReSharper.TestRunner.Abstractions.IClientEndpoint.System.Threading.Tasks.Task`1[JetBrains.ReSharper.TestRunner.Abstractions.Objects.IAutoRegisterInProtocol] SendMessage(JetBrains.ReSharper.TestRunner.Abstractions.Objects.IAutoRegisterInProtocol)_proxy` (2763052212960334136), taskId=1000006
   -> call `ServerSocket-<noname>.JetBrains.ReSharper.TestRunner.Abstractions.IClientEndpoint.System.Threading.Tasks.Task`1[JetBrains.ReSharper.TestRunner.Abstractions.Objects.IAutoRegisterInProtocol] SendMessage(JetBrains.ReSharper.TestRunner.Abstractions.Objects.IAutoRegisterInProtocol)_proxy` (2763052212960334136), taskId=1000006
”

--- Outer ---

--- EXCEPTION #2/2 [LoggerException]
Message = “
  Method not found: 'System.Threading.Tasks.ValueTask Xunit.v3.InProcessFrontController.Find(Xunit.Sdk.IMessageSink, Xunit.Sdk.ITestFrameworkDiscoveryOptions, System.Func`2<Xunit.Sdk.ITestCase,Boolean>, System.Type[], System.Func`3<Xunit.Sdk.ITestCase,Boolean,System.Threading.Tasks.ValueTask`1<Boolean>>)'., reason: System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask Xunit.v3.InProcessFrontController.Find(Xunit.Sdk.IMessageSink, Xunit.Sdk.ITestFrameworkDiscoveryOptions, System.Func`2<Xunit.Sdk.ITestCase,Boolean>, System.Type[], System.Func`3<Xunit.Sdk.ITestCase,Boolean,System.Threading.Tasks.ValueTask`1<Boolean>>)'.
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.TestDiscoverer.Run(CancellationToken ct)
     at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.TestDiscoverer.Run(CancellationToken ct)
     at JetBrains.ReSharper.TestRunner.Adapters.XUnit3.XUnitRunner.RunTestsAsync(TestRunRequest request, ITestDiscoverySink discoverySink, ITestExecutionSink executionSink) in Z:\BuildAgent\work\1b668fe37ef92293\ReSharperTestRunner\src\Adapters\TestRunner.Adapters.XUnit3\XUnitRunner.cs:line 76
”
InnerException = “Exception #1 at Root.InnerException”
StackTraceString = “
  at JetBrains.Util.ILoggerEx.LogException(ILogger logger, LoggingLevel level, Exception exception, ExceptionOrigin exceptionOrigin, String comment) in LogException.il:line IL_002E mvid 91BE
     at JetBrains.Util.ILoggerEx.Error(ILogger logger, Exception exception, ExceptionOrigin origin, String comment) in Error.il:line IL_0000 mvid 91BE
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.Start(CancellationToken onCancel, CancellationToken onAbort) in Start.il:line IL_0182 mvid FCFC
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 243A
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 243A
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 243A
     at JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestRun.StartCore(CancellationToken onCancel, CancellationToken onAbort) in StartCore.il:line IL_03B3 mvid FCFC
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 243A
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 243A
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 243A
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerRunStrategy.Run(IUnitTestRun run) in Run.il:line IL_01C8 mvid FCFC
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 243A
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 243A
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 243A
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.RunTests(CancellationToken cancelCt, CancellationToken abortCt) in RunTests.il:line IL_00AE mvid FCFC or RunTests.il:line IL_02D6 mvid FCFC
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 243A
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 243A
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 243A
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.CancelIf(Task task, CancellationToken ct, TaskCreationOptions options) in CancelIf.il:line IL_0126 mvid FCFC
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 243A
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in TrySetResult.il:line IL_004B mvid 243A
     at System.Threading.Tasks.Task.TwoTaskWhenAnyPromise`1.Invoke(Task completingTask) in Invoke.il:line IL_0088 mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 243A
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 243A
     at JetBrains.ReSharper.UnitTestFramework.Common.Extensions.TaskExtensions.ThrowIf[TException](Task task, Task signallingTask, Func`1 exceptionFactory) in ThrowIf.il:line IL_0118 mvid FCFC
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 243A
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task`1.TrySetResult(TResult result) in TrySetResult.il:line IL_004B mvid 243A
     at System.Threading.Tasks.Task.TwoTaskWhenAnyPromise`1.Invoke(Task completingTask) in Invoke.il:line IL_0088 mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 243A
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 243A
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.TestRunnerAgentManager.TestRunnerExecutionAgent.<RunTests>b__8_1()
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 243A
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 243A
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetException(Exception exception, Task`1& taskField) in SetException.il:line IL_0025 mvid 243A
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.Activation.ServerMessageBroker.SendMessage(IMessage message) in SendMessage.il:line IL_0077 mvid FCFC
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s) in ExecutionContextCallback.il:line IL_0000 mvid 243A
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread) in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext() in MoveNext.il:line IL_0000 mvid 243A or MoveNext.il:line IL_0040 mvid 243A
     at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining) in RunOrScheduleAction.il:line IL_003B mvid 243A
     at System.Threading.Tasks.Task.RunContinuations(Object continuationObject) in RunContinuations.il:line IL_0065 mvid 243A or RunContinuations.il:line IL_0090 mvid 243A
     at System.Threading.Tasks.Task.FinishSlow(Boolean userDelegateExecute) in FinishSlow.il:line IL_0003 mvid 243A
     at System.Threading.Tasks.Task.TrySetException(Object exceptionObject) in TrySetException.il:line IL_0022 mvid 243A
     at System.Threading.Tasks.TaskCompletionSource`1.TrySetException(Exception exception) in TrySetException.il:line IL_000A mvid 243A
     at System.Threading.Tasks.TaskCompletionSource`1.SetException(Exception exception) in SetException.il:line IL_0000 mvid 243A
     at JetBrains.Rd.Reflection.ProxyGeneratorUtil.<>c__DisplayClass0_0`1.<ToTask>b__0(RdTaskResult`1 r) in ProxyGeneratorUtil.il:line IL_0039 mvid 45DA
     at JetBrains.Collections.Viewable.SignalBase`1.Fire(T value) in Fire.il:line IL_0028 mvid 2A6A
     at JetBrains.Collections.Viewable.WriteOnceProperty`1.WriteOnceSignal.Fire(T value) in Fire.il:line IL_0000 mvid 2A6A
     at JetBrains.Collections.Viewable.WriteOnceProperty`1.SetIfEmpty(T newValue) in SetIfEmpty.il:line IL_003A mvid 2A6A
     at JetBrains.Rd.Tasks.WiredRdTask`2.CallSite.<>c__DisplayClass5_0.<OnWireReceived>b__0() in CallSite.il:line IL_0000 mvid 82A2
     at JetBrains.Rd.Impl.MessageBroker.RdWireableDispatchHelper.<>c__DisplayClass12_0.<DoDispatch>b__0() in RdWireableDispatchHelper.il:line IL_008B mvid 82A2
     at JetBrains.ReSharper.UnitTestFramework.Execution.TestRunner.Activation.TestRunnerAgentServerHub.InternRootScheduler.Queue(Action action) in Queue.il:line IL_0000 mvid FCFC
     at JetBrains.Rd.Impl.MessageBroker.RdWireableDispatchHelper.DoDispatch(Lifetime lifetime, IScheduler scheduler, Action action) in DoDispatch.il:line IL_00BD mvid 82A2
     at JetBrains.Rd.Tasks.WiredRdTask`2.CallSite.OnWireReceived(IProtocol proto, SerializationCtx ctx, UnsafeReader reader, IRdWireableDispatchHelper dispatchHelper) in OnWireReceived.il:line IL_0157 mvid 82A2
     at JetBrains.Rd.Tasks.WiredRdTask`2.OnWireReceived(UnsafeReader reader, IRdWireableDispatchHelper dispatchHelper) in OnWireReceived.il:line IL_0071 mvid 82A2
     at JetBrains.Rd.Impl.MessageBroker.DispatchImpl(Byte[] msg) in DispatchImpl.il:line IL_0112 mvid 82A2
     at JetBrains.Rd.Impl.MessageBroker.Dispatch(Byte[] msg) in Dispatch.il:line IL_0038 mvid 82A2
     at JetBrains.Diagnostics.LogEx.Catch(ILog log, Action action) in Catch.il:line IL_0000 mvid 2A6A
     at JetBrains.Rd.Impl.SocketWire.Base.ReadMsg() in ReadMsg.il:line IL_00BC mvid 82A2
     at JetBrains.Rd.Impl.SocketWire.Base.ReceiverProc(Socket socket) in ReceiverProc.il:line IL_006C mvid 82A2
     at JetBrains.Rd.Impl.SocketWire.Base.<>c__DisplayClass19_0.<.ctor>b__1(Socket socket) in Base.il:line IL_005C mvid 82A2
     at JetBrains.Collections.Viewable.SignalBase`1.Fire(T value) in Fire.il:line IL_0028 mvid 2A6A
     at JetBrains.Collections.Viewable.ViewableProperty`1.set_Value(T value)
     at JetBrains.Rd.Impl.SocketWire.Server.<>c__DisplayClass4_0.<StartServerSocket>b__1() in Server.il:line IL_0022 mvid 82A2 or Server.il:line IL_00F6 mvid 82A2
     at JetBrains.Diagnostics.LogEx.Catch(ILog log, Action action) in Catch.il:line IL_0000 mvid 2A6A
     at JetBrains.Rd.Impl.SocketWire.Server.<>c__DisplayClass4_0.<StartServerSocket>b__0() in Server.il:line IL_0022 mvid 82A2 or Server.il:line IL_00F6 mvid 82A2
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) in RunInternal.il:line IL_0040 mvid 243A
”
ExceptionPath = Root
ClassName = JetBrains.Util.LoggerException
HResult = COR_E_APPLICATION=80131600

```

**Comment by mharrah** [comment]
Confirmed.  When I downgraded back to xUnit v3 1.1.0, normal functionality returned.

**Comment by bradwilson** [comment]
Given that this is listed as a breaking change for 2.0.0, it certainly seems like this is a JetBrains runner issue.

**Comment by m-moris** [comment]
I found a related Issue on youtrack on reshaper

https://youtrack.jetbrains.com/issue/RSRP-500210/Updating-to-xunit.v3-2.0.0-results-in-MethodNotFoundException

**Comment by ken-swyfft** [comment]
I'll just add - I'm not sure how the decision was made to introduce this breaking change, but my recommendation would be that before you remove methods that are likely to break things, you flag the method as `[Obsolete]` and give it six months or so for downstream users to migrate, before actually removing the method.

**Comment by bradwilson** [comment]
In this case it was essentially impossible to leave these classes in place as-is, and as a single person supporting this code base, the best thing I could do is just make the change and cut it over instead of creating an entirely new class hierarchy with a bunch of things named Foo2 of FooEx.

Apologies that this caused issues, but there was no realistic way for me to be able to do anything else.

**Comment by velvolue** [comment]
Just updated Rider to version 2024.3.7 and the test runner is now working with xunit.v3 2.0.0 🎉

**Comment by alexaka1** [comment]
I also updated, but I'm still having issues. I'll do some more tests next week, but right now I still have "this test cannot be run, see why" messages.

**Comment by bradwilson** [comment]
@alexaka1 We don't support Resharper, JetBrains does. You should open issues in their issue tracker to get them addressed by their team. AFAIK they do not monitor issues here (nor should they be expected to, IMO).

Thanks!

**Comment by alexaka1** [comment]
I know, I just gave feedback that it isn't fixed on JetBrains' side.
