### ISSUE TITLE
Issues with the fixer for xUnit2023

### ISSUE THREAD

**Issue by glen-84** [xunit/xunit#3336]
**Issue 1**

```cs
        // assert
        Assert.Collection(list, s => Assert.Equal(_strings[0], s));
```

Is fixed to:

```cs
        // assert
        var s = // assert
Assert.Single(list);
        Assert.Equal(_strings[0], s);
```

(duplicated comment, missing indentation)

**Issue 2**

Many cases are flagged but the fixer doesn't do anything. For example:

```cs
        Assert.Collection(result.Errors,
            error => Assert.Equal(
                "Response status code does not indicate success: 404 (Not Found).",
                error.Message));

        Assert.Collection(
            type.Locations.AsEnumerable(),
            t => Assert.Equal(DirectiveLocation.Query, t));

        Assert.Collection(
            query.Fields["address"].Directives,
            item => Assert.Equal(FederationTypeNames.ExternalDirective_Name, item.Type.Name));
```

(there are much more complicated cases, though)

**Issue 3**

```cs
        Assert.True(success1);
        Assert.Collection(registered1, t => Assert.Equal("abc", t.Id));
        Assert.False(success2);
        Assert.Collection(registered2, t => Assert.Equal("abc", t.Id));
```

Is fixed to:

```cs
        Assert.True(success1);
        var t = Assert.Single(registered1);
        Assert.Equal("abc", t.Id);
        Assert.False(success2);
        var t = Assert.Single(registered2);
        Assert.Equal("abc", t.Id);
```

(variable `t` is used twice ... not as big a deal, but could possibly have a numeric suffix added/incremented)

**Comment by bradwilson** [comment]
I agree that issue 1 and 2 should be fixed.

Is your issue 3 sample correct? That code shouldn't compile.

**Comment by bradwilson** [comment]
When I tried to reproduce this using the fixer on your third issue, this was the code that was generated:

```csharp
        Assert.True(success1);
        var t = Assert.Single(registered1);
        Assert.Equal("abc", t.Id);
        Assert.False(success2);
        var t_2 = Assert.Single(registered2);
        Assert.Equal("abc", t_2.Id);
```

**Comment by glen-84** [comment]
It happens if you fix them together using `Fix All` in VS Code.

**Comment by bradwilson** [comment]
I doubt there will be anything that can be done there, since it's asking for the changes independently.

**Comment by bradwilson** [comment]
You should report that as a bug to VS Code.

**Comment by glen-84** [comment]
I don't think that it's a VS Code issue – I think that it's a result of the [FixAllProvider](https://github.com/dotnet/roslyn/blob/2b7ef41329fb7405388f73d899240c21761ba1f3/docs/analyzers/FixAllProvider.md) that you're using (the `BatchFixer`), which fixes each issue independently based on the original source code.

**Comment by bradwilson** [comment]
I've removed the batch fixer. This presumably will prevent "Fix All" and thus prevent any bugs related to this.

Fixed in `1.23.0-pre.6` https://xunit.net/docs/using-ci-builds

**Comment by glen-84** [comment]
@bradwilson What about issues 1 and 2? Shouldn't this issue remain open? 🙂

**Comment by JazzGlobal** [comment]
Think I can claim this? Looking to contribute 😁

**Comment by bradwilson** [comment]
@JazzGlobal Sure, it's marked as "help wanted", so feel free to send a PR!

**Comment by bradwilson** [comment]
Fix for issue 1 is available in `2.0.0-pre.59` https://xunit.net/docs/using-ci-builds
